# Generated by Django 3.1.2 on 2020-10-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('since', models.DateField()),
                ('until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_lang', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=256)),
                ('tech_stack', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2048)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmeta')),
            ],
        ),
    ]
