# Generated by Django 3.1.2 on 2020-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='projectmeta',
            name='homepage',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='projectmeta',
            name='languages',
            field=models.CharField(blank=True, max_length=512, verbose_name='langs'),
        ),
        migrations.AlterField(
            model_name='projectmeta',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectmeta',
            name='tools',
            field=models.CharField(blank=True, max_length=512, verbose_name='tools'),
        ),
    ]
