# Generated by Django 3.1.2 on 2020-10-05 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('email', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=16)),
                ('interests', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='InformationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_lang', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=2048)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informations.informationmeta')),
            ],
        ),
    ]
