# Generated by Django 3.1.2 on 2020-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_auto_20201006_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationmeta',
            name='interests',
        ),
        migrations.AddField(
            model_name='informationdetail',
            name='interests',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
