# Generated by Django 3.1.2 on 2020-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_auto_20201006_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationmeta',
            name='skills',
        ),
        migrations.AddField(
            model_name='informationdetail',
            name='skills',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
